Style/Documentation:
  Enabled: false
  
Style/AsciiComments:
  Enabled: false
  
Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false